import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourceDirectory = join(repositoryRoot, 'content', 'guides');
const outputPath = join(repositoryRoot, 'lib', 'generated-guides.ts');

function parseFrontMatter(source, filename) {
  const match = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) {
    return null;
  }

  const metadata = Object.fromEntries(
    match[1]
      .split('\n')
      .filter(Boolean)
      .map((line) => {
        const separator = line.indexOf(':');
        if (separator === -1) {
          throw new Error(`${filename}: invalid front matter line "${line}"`);
        }
        return [line.slice(0, separator).trim(), line.slice(separator + 1).trim()];
      }),
  );

  for (const field of ['slug', 'title', 'summary', 'exercise', 'order']) {
    if (!metadata[field]) {
      throw new Error(`${filename}: missing front matter field "${field}"`);
    }
  }

  const order = Number(metadata.order);
  if (!Number.isInteger(order) || order < 1) {
    throw new Error(`${filename}: order must be a positive integer`);
  }

  return {
    slug: metadata.slug,
    title: metadata.title,
    summary: metadata.summary,
    exercise: metadata.exercise,
    order,
    markdown: match[2].trim(),
  };
}

const filenames = (await readdir(sourceDirectory))
  .filter((filename) => filename.endsWith('.md'))
  .sort();
const guides = [];

for (const filename of filenames) {
  const source = await readFile(join(sourceDirectory, filename), 'utf8');
  const guide = parseFrontMatter(source, filename);
  if (guide) {
    guides.push(guide);
  }
}

guides.sort((left, right) => left.order - right.order);

if (new Set(guides.map((guide) => guide.slug)).size !== guides.length) {
  throw new Error('Guide slugs must be unique');
}
if (new Set(guides.map((guide) => guide.order)).size !== guides.length) {
  throw new Error('Guide order values must be unique');
}

const output = `// Generated by scripts/build-guides.mjs. Edit content/guides/*.md instead.

export type GuideExercise = 'all' | 'assembly' | 'hybrid' | 'typing' | 'outbreak';

export interface ParticipantGuide {
  slug: string;
  title: string;
  summary: string;
  exercise: GuideExercise;
  order: number;
  markdown: string;
}

export const PARTICIPANT_GUIDES: ParticipantGuide[] = ${JSON.stringify(guides, null, 2)};

export function participantGuide(slug: string) {
  return PARTICIPANT_GUIDES.find((guide) => guide.slug === slug);
}
`;

await writeFile(outputPath, output, 'utf8');
console.log(`Built ${guides.length} participant guides`);
